// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.1
// source: hellogrpc.proto

package HelloGrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hellogrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hellogrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_hellogrpc_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GreetMessage) Reset() {
	*x = GreetMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hellogrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetMessage) ProtoMessage() {}

func (x *GreetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hellogrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetMessage.ProtoReflect.Descriptor instead.
func (*GreetMessage) Descriptor() ([]byte, []int) {
	return file_hellogrpc_proto_rawDescGZIP(), []int{1}
}

func (x *GreetMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_hellogrpc_proto protoreflect.FileDescriptor

var file_hellogrpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x22, 0x22, 0x0a, 0x0c,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x20, 0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0x4e, 0x0a, 0x09, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x12,
	0x41, 0x0a, 0x0b, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x17,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47,
	0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x42, 0x2d, 0x0a, 0x1e, 0x69, 0x6f, 0x2e, 0x74, 0x6f, 0x6b, 0x69, 0x6b, 0x6f, 0x6b,
	0x6f, 0x6b, 0x6f, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x42, 0x09, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x50,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hellogrpc_proto_rawDescOnce sync.Once
	file_hellogrpc_proto_rawDescData = file_hellogrpc_proto_rawDesc
)

func file_hellogrpc_proto_rawDescGZIP() []byte {
	file_hellogrpc_proto_rawDescOnce.Do(func() {
		file_hellogrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_hellogrpc_proto_rawDescData)
	})
	return file_hellogrpc_proto_rawDescData
}

var file_hellogrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hellogrpc_proto_goTypes = []interface{}{
	(*GreetRequest)(nil), // 0: HelloGrpc.GreetRequest
	(*GreetMessage)(nil), // 1: HelloGrpc.GreetMessage
}
var file_hellogrpc_proto_depIdxs = []int32{
	0, // 0: HelloGrpc.HelloGrpc.GreetServer:input_type -> HelloGrpc.GreetRequest
	1, // 1: HelloGrpc.HelloGrpc.GreetServer:output_type -> HelloGrpc.GreetMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hellogrpc_proto_init() }
func file_hellogrpc_proto_init() {
	if File_hellogrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hellogrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hellogrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hellogrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hellogrpc_proto_goTypes,
		DependencyIndexes: file_hellogrpc_proto_depIdxs,
		MessageInfos:      file_hellogrpc_proto_msgTypes,
	}.Build()
	File_hellogrpc_proto = out.File
	file_hellogrpc_proto_rawDesc = nil
	file_hellogrpc_proto_goTypes = nil
	file_hellogrpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloGrpcClient is the client API for HelloGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloGrpcClient interface {
	// Sends a greeting
	GreetServer(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetMessage, error)
}

type helloGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloGrpcClient(cc grpc.ClientConnInterface) HelloGrpcClient {
	return &helloGrpcClient{cc}
}

func (c *helloGrpcClient) GreetServer(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetMessage, error) {
	out := new(GreetMessage)
	err := c.cc.Invoke(ctx, "/HelloGrpc.HelloGrpc/GreetServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloGrpcServer is the server API for HelloGrpc service.
type HelloGrpcServer interface {
	// Sends a greeting
	GreetServer(context.Context, *GreetRequest) (*GreetMessage, error)
}

// UnimplementedHelloGrpcServer can be embedded to have forward compatible implementations.
type UnimplementedHelloGrpcServer struct {
}

func (*UnimplementedHelloGrpcServer) GreetServer(context.Context, *GreetRequest) (*GreetMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetServer not implemented")
}

func RegisterHelloGrpcServer(s *grpc.Server, srv HelloGrpcServer) {
	s.RegisterService(&_HelloGrpc_serviceDesc, srv)
}

func _HelloGrpc_GreetServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloGrpcServer).GreetServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloGrpc.HelloGrpc/GreetServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloGrpcServer).GreetServer(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HelloGrpc.HelloGrpc",
	HandlerType: (*HelloGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GreetServer",
			Handler:    _HelloGrpc_GreetServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hellogrpc.proto",
}
